### ISSUE TITLE
Bug: Modifier UI not loading for Areas in separate windows

### ISSUE THREAD

**Issue by Neltulz** [Symstract/modifier_list#5] opened 2019-12-05 06:04 UTC
Blender version: 2.81 Stable
OS: Win10 Pro 64bit
Modifier List v1.4.2

Whenever I restart Blender, the modifier area is empty.  I am assuming it has to do with the area being inside of a separate window.  This just happens to be how I prefer to use Blender because I can maximize the 3d viewport without losing view of my outliner and properties editors.

![2019-12-04_23-56-20](https://user-images.githubusercontent.com/7741742/70208116-54462000-16f2-11ea-810d-2b5dec8540f0.png)

Toggling this option OFF/ON causes it to load.

![2019-12-04_23-59-28](https://user-images.githubusercontent.com/7741742/70208123-57d9a700-16f2-11ea-8e9f-de6332970990.png)

Hopefully this is an easy fix! :)

**Comment by Symstract** [comment] 2019-12-07 22:23
I can't reproduce this. Do you see some error message in the console?

**Comment by Neltulz** [comment] 2019-12-10 05:56
> I can't reproduce this. Do you see some error message in the console?

Hi, I went ahead and created a fresh Blender install and created a config folder to make it a self contained (portable) installation of blender 2.81.

I tried to recreate my layout and the "modifier list" properties loads without any issues every time I restart blender.  So, there must be something wrong with my primary blender install.

I checked the log, and there do not appear to be any errors.

I think it might be time I migrated to a new blender config, anway.  This one is becoming more and more problematic by the day.  Sorry for reporting a bug without testing it on a clean install.

**Comment by Symstract** [comment] 2019-12-10 15:14
Good to hear that it got resolved :) Closing then.

**Closed by Symstract** 2019-12-10 15:14 UTC

**Comment by Neltulz** [comment] 2019-12-11 21:35
Sorry to re-open this, but I just wanted to add one last thing, and then you can immediately close this again.

I figured out what the problem was.  I had the modifier list addon disabled in the workspace.  Re-enabling it here, saving startup settings, and then restarting Blender causes the addon to function properly! :)  I am learning that, this "filter addon's" feature does a lot more than simply hide tabs from the sidebar.  It botches necessary functionality of many add-ons.  I may stop using this feature.

![2019-12-11_15-31-27](https://user-images.githubusercontent.com/7741742/70662320-95c35780-1c2b-11ea-8ff7-904ccad95b04.png)
