### ISSUE TITLE
No output attributes in the geometry nodes modifier

### ISSUE THREAD

**Issue by Oxicid** [Symstract/modifier_list#24] opened 2021-11-10 18:10 UTC
The output attribute of the Geometry Nodes modifier works with errors, it is necessary to switch List to Stack. 

There is also a problem with deleting modifier after these switches

Blender Version: blender-3.0.0-beta+v30.ab7214ca2ef9-windows.amd64-relea

https://user-images.githubusercontent.com/76912541/141169255-742d5725-a3ce-45e0-989b-be7294d92cdb.mp4

se

**Comment by Symstract** [comment] 2021-11-13 15:03
Thanks for the report.

I try to keep track of changes in Blender, so I'm aware that the addon is missing some features in Blender 3.0. I'll release an update at some point, quite soon maybe. So, I'm closing this since this doesn't need to be tracked separately.

For the problem with switching from stack to list, I can't, unfortunately, do anything because it's not a bug in the addon. I might report it as a bug in Blender.

**Closed by Symstract** 2021-11-13 15:03 UTC
