### ISSUE TITLE
Geometry nodes modifier Outputs / Inputs not displayed correctly

### ISSUE THREAD

**Issue by fleity** [Symstract/modifier_list#28] opened 2022-02-01 21:41 UTC
![Screenshot 2022-02-01 223355](https://user-images.githubusercontent.com/7192666/152055910-a4b6db1b-b9ea-4d18-9dc9-fcd1763b4944.jpg)
 The addon is amazing hence I want to report this bug to make it even better. The geometry nodes modifier is not displayed correctly (blender 3.0.0, modifier_list 1.7.2).
 The input and output attributes are not listed and nameable.

**Comment by Symstract** [comment] 2022-02-03 18:13
Thanks for the report. I've released an update: https://github.com/Symstract/modifier_list/releases.
See if the bug is fixed in the new version. If not, check if there is some error in the console and I'll investigate.

**Comment by fleity** [comment] 2022-02-03 18:44
when first launching blender the panel still does not look correct. 

steps:
1. launch
2. create cube
3. add geom nodes modifier

looks like this, no errors in the console
![image](https://user-images.githubusercontent.com/7192666/152407771-e2358d25-4b00-4fc8-ba74-ba52174dd464.png)

curiously it is only broken in the List style Properties Editor, it is correct in the stack style view 
![image](https://user-images.githubusercontent.com/7192666/152408094-42c4efcc-08a9-4bf3-8a5c-818b67db2c1b.png)

but switching from list to stack and back results in both being visible?
![image](https://user-images.githubusercontent.com/7192666/152408161-ec8c5a96-baf0-46a6-860b-dbc5c9a42fd1.png)

**Comment by Symstract** [comment] 2022-02-03 19:01
But it seems that you don't have any inputs or outputs connected in the example? In that case, Modifier List doesn't show anything in the modifier, apart from the node tree selector. If you add some inputs, do they appear in the modifier?

With the stack layout, modifier layouts always work because they are the same ones the regular UI uses. The issue that the list and stack appear at the same time after switching the style is caused by a bug in Blender.

**Comment by fleity** [comment] 2022-02-03 19:31
... you are right... I am so sorry.  When setting it up properly it does work perfectly.
![image](https://user-images.githubusercontent.com/7192666/152415409-182ac7c8-6003-4240-a617-d8b5f395b475.png)

**Closed** 2022-02-03 19:32 UTC

**Comment by Symstract** [comment] 2022-02-03 19:33
That's great to hear :)
